spring:
  cloud:
    nacos:
      discovery:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service-local
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/user/**
        - id: content-service-local
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/article/**,/category/**,/file/**
        - id: social-service-local
          uri: http://127.0.0.1:8084
          predicates:
            - Path=/social/**,/report/**
        - id: recommend-service-local
          uri: http://127.0.0.1:8086
          predicates:
            - Path=/hot-article/**
        - id: search-service-local
          uri: http://127.0.0.1:8087
          predicates:
            - Path=/search/**
