export const avatarCropperConfig = {
  title: '裁剪头像',
  okText: '确认使用',
  cancelText: '取消',
  width: 520,
  aspect: 1,
  cropShape: 'round' as const,
  showGrid: false,
  zoomMin: 0.1,
  zoomMax: 10,
  zoomStep: 0.01,
  zoomLabel: '缩放',
  hint: '可缩小或放大图片，拖动调整位置，滑动或输入倍率调整大小',
  errorMessage: '裁剪失败，请重试',
} as const;
