-- 统一人工审核工单
CREATE TABLE IF NOT EXISTS t_moderation_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '工单ID',
    task_type VARCHAR(32) NOT NULL COMMENT 'REPORT/ARTICLE_AUDIT/PROFILE_AUDIT',
    source_id BIGINT NOT NULL COMMENT '来源业务ID，如 reportId/articleId/auditTaskId',
    target_type INT DEFAULT NULL COMMENT '目标类型，与举报类型一致',
    target_id BIGINT DEFAULT NULL COMMENT '目标ID',
    subject_user_id BIGINT DEFAULT NULL COMMENT '被审核内容作者/被举报人',
    reporter_id BIGINT DEFAULT NULL COMMENT '举报人，仅举报类',
    reason VARCHAR(512) DEFAULT NULL COMMENT '举报原因或审核说明',
    summary VARCHAR(512) DEFAULT NULL COMMENT '内容摘要（前三行）',
    extra_payload VARCHAR(512) DEFAULT NULL COMMENT '扩展信息，如资料字段名',
    target_status_snapshot VARCHAR(64) DEFAULT NULL COMMENT '目标状态快照，如 ARTICLE_PENDING/PROFILE_HUMAN_REVIEW',
    target_updated_at DATETIME DEFAULT NULL COMMENT '目标内容更新时间快照',
    status INT NOT NULL DEFAULT 0 COMMENT '0未处理 1处理中 2已完成',
    handle_action VARCHAR(32) DEFAULT NULL COMMENT '处理结果动作',
    handler_id BIGINT DEFAULT NULL COMMENT '处理人',
    handle_remark VARCHAR(255) DEFAULT NULL COMMENT '处理备注',
    claim_time DATETIME DEFAULT NULL COMMENT '认领时间',
    handle_time DATETIME DEFAULT NULL COMMENT '处理完成时间',
    claim_token VARCHAR(64) NOT NULL DEFAULT '' COMMENT '认领租约令牌',
    lease_expire_time DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '认领租约到期时间',
    action_request_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '当前处理请求幂等标识',
    last_error VARCHAR(255) NOT NULL DEFAULT '' COMMENT '最近一次处理错误',
    attempt_count INT NOT NULL DEFAULT 0 COMMENT '处理尝试次数',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    active_source_key VARCHAR(96) GENERATED ALWAYS AS
        (CASE WHEN status IN (0, 1) THEN CONCAT(task_type, ':', source_id) ELSE NULL END) STORED,
    UNIQUE KEY uk_moderation_active_source (active_source_key),
    KEY idx_moderation_status_type_time (status, task_type, create_time, id),
    KEY idx_moderation_status_lease (status, lease_expire_time, id),
    KEY idx_moderation_handler (handler_id, status, update_time),
    KEY idx_moderation_type_source (task_type, source_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='统一人工审核工单';

CREATE TABLE IF NOT EXISTS t_audit_notification_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_key VARCHAR(96) NOT NULL,
    payload JSON NOT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_time DATETIME DEFAULT NULL,
    lock_token VARCHAR(64) DEFAULT NULL,
    lock_time DATETIME DEFAULT NULL,
    last_error VARCHAR(1000) DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_audit_notification_outbox_event (event_key),
    KEY idx_audit_notification_outbox_pending (status, next_retry_time, id),
    KEY idx_audit_notification_outbox_lock (status, lock_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审核通知可靠事件 Outbox';
